### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by atm-ph** [ATM-Consulting/dolibarr_module_nomenclature#44]
https://github.com/ATM-Consulting/dolibarr_module_nomenclature/blob/0152ac26d722addadc10ef535d57b871147f48e8/core/triggers/interface_50_modnomenclature_nomenclaturetrigger.class.php#L304

@atm-florian 
Je sais que ça date (1 an) mais tu pourrais m'expliquer que fait un attribut custom ici ? (totalPRC_fruidoraix)
Je ne parle pas des autres attributs qui sont faux (txtva, txlocaltax1, ...)

**Comment by atm-florian** [comment]
What, dans la master ?! ca n'a rien à foutre ici, au pire dans la branche master_fruidorex, mais pas ici, putin j'imagine que c'est un merge malheureux.... On on ne la pas vue avant....

**Comment by atm-ph** [comment]
#11
