### ISSUE TITLE
Grip pour réorganisation

### ISSUE THREAD

**Issue by atm-geoffrey** [ATM-Consulting/dolibarr_module_nomenclature#5]
Ajouter un grip en fin de ligne (comme sur les devis, commande, facture, etc) pour permettre d'ordonner les postes de travail liés à une nomenclature

**Comment by ATM-Nicolas** [comment]
Ce n'est pas reproductible sur la master et sur la 1.0

**Comment by atm-maxime** [comment]
C'est pas que c'est pas reproductible c'est que ça a été développé depuis la demande de geoff :)
![image](https://user-images.githubusercontent.com/2097773/33929903-61db9604-dfeb-11e7-81d4-5ada8428ccff.png)
